CREATE TABLE `crypt` (
  `id` int NOT NULL,
  `name` varchar(250) COLLATE utf8mb4_unicode_ci NOT NULL,
  `aka` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clan` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `adv` boolean DEFAULT NULL,
  `group` smallint NOT NULL,
  `capacity` smallint NOT NULL,
  `disciplines` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `text` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `set` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `banned` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `artist` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abombwe` tinyint NOT NULL,
  `animalism` tinyint NOT NULL,
  `auspex` tinyint NOT NULL,
  `celerity` tinyint NOT NULL,
  `chimerstry` tinyint NOT NULL,
  `daimoinon` tinyint NOT NULL,
  `dementation` tinyint NOT NULL,
  `dominate` tinyint NOT NULL,
  `fortitude` tinyint NOT NULL,
  `melpominee` tinyint NOT NULL,
  `mytherceria` tinyint NOT NULL,
  `necromancy` tinyint NOT NULL,
  `obeah` tinyint NOT NULL,
  `obfuscate` tinyint NOT NULL,
  `obtenebration` tinyint NOT NULL,
  `potence` tinyint NOT NULL,
  `presence` tinyint NOT NULL,
  `protean` tinyint NOT NULL,
  `quietus` tinyint NOT NULL,
  `sanguinus` tinyint NOT NULL,
  `serpentis` tinyint NOT NULL,
  `spiritus` tinyint NOT NULL,
  `temporis` tinyint NOT NULL,
  `thanatosis` tinyint NOT NULL,
  `thaumaturgy` tinyint NOT NULL,
  `valeren` tinyint NOT NULL,
  `vicissitude` tinyint NOT NULL,
  `visceratika` tinyint NOT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modification_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FULLTEXT KEY (name, aka)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
