CREATE TABLE IF NOT EXISTS `deck_archetype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `icon` VARCHAR(250) DEFAULT NULL,
  `type` VARCHAR(50) NOT NULL,
  `description` TEXT DEFAULT NULL,
  `deck_id` VARCHAR(250) DEFAULT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modification_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_deck_archetype_name`(`name`),
  FOREIGN KEY (`deck_id`) REFERENCES `deck`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

